# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'check_health_in_progress.ui'
##
## Created by: Qt User Interface Compiler version 6.10.1
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QMetaObject, QRect, Qt)
from PySide6.QtGui import (QBrush, QColor, QFont, QPalette)
from PySide6.QtWidgets import (QLabel)

class Ui_check_health_in_progress(object):
    def setupUi(self, check_health_in_progress):
        if not check_health_in_progress.objectName():
            check_health_in_progress.setObjectName(u"check_health_in_progress")
        check_health_in_progress.resize(650, 600)
        palette = QPalette()
        brush = QBrush(QColor(255, 255, 255, 255))
        brush.setStyle(Qt.BrushStyle.SolidPattern)
        palette.setBrush(QPalette.ColorGroup.Active, QPalette.ColorRole.WindowText, brush)
        brush1 = QBrush(QColor(48, 34, 93, 255))
        brush1.setStyle(Qt.BrushStyle.SolidPattern)
        palette.setBrush(QPalette.ColorGroup.Active, QPalette.ColorRole.Button, brush1)
        brush2 = QBrush(QColor(72, 51, 139, 255))
        brush2.setStyle(Qt.BrushStyle.SolidPattern)
        palette.setBrush(QPalette.ColorGroup.Active, QPalette.ColorRole.Light, brush2)
        brush3 = QBrush(QColor(60, 42, 116, 255))
        brush3.setStyle(Qt.BrushStyle.SolidPattern)
        palette.setBrush(QPalette.ColorGroup.Active, QPalette.ColorRole.Midlight, brush3)
        brush4 = QBrush(QColor(24, 17, 46, 255))
        brush4.setStyle(Qt.BrushStyle.SolidPattern)
        palette.setBrush(QPalette.ColorGroup.Active, QPalette.ColorRole.Dark, brush4)
        brush5 = QBrush(QColor(32, 23, 62, 255))
        brush5.setStyle(Qt.BrushStyle.SolidPattern)
        palette.setBrush(QPalette.ColorGroup.Active, QPalette.ColorRole.Mid, brush5)
        palette.setBrush(QPalette.ColorGroup.Active, QPalette.ColorRole.Text, brush)
        palette.setBrush(QPalette.ColorGroup.Active, QPalette.ColorRole.BrightText, brush)
        palette.setBrush(QPalette.ColorGroup.Active, QPalette.ColorRole.ButtonText, brush)
        brush6 = QBrush(QColor(0, 0, 0, 255))
        brush6.setStyle(Qt.BrushStyle.SolidPattern)
        palette.setBrush(QPalette.ColorGroup.Active, QPalette.ColorRole.Base, brush6)
        palette.setBrush(QPalette.ColorGroup.Active, QPalette.ColorRole.Window, brush1)
        palette.setBrush(QPalette.ColorGroup.Active, QPalette.ColorRole.Shadow, brush6)
        palette.setBrush(QPalette.ColorGroup.Active, QPalette.ColorRole.AlternateBase, brush4)
        brush7 = QBrush(QColor(255, 255, 220, 255))
        brush7.setStyle(Qt.BrushStyle.SolidPattern)
        palette.setBrush(QPalette.ColorGroup.Active, QPalette.ColorRole.ToolTipBase, brush7)
        palette.setBrush(QPalette.ColorGroup.Active, QPalette.ColorRole.ToolTipText, brush6)
        brush8 = QBrush(QColor(255, 255, 255, 127))
        brush8.setStyle(Qt.BrushStyle.SolidPattern)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette.setBrush(QPalette.ColorGroup.Active, QPalette.ColorRole.PlaceholderText, brush8)
#endif
#if QT_VERSION >= QT_VERSION_CHECK(6, 6, 0)
        palette.setBrush(QPalette.ColorGroup.Active, QPalette.ColorRole.Accent, brush6)
#endif
        palette.setBrush(QPalette.ColorGroup.Inactive, QPalette.ColorRole.WindowText, brush)
        palette.setBrush(QPalette.ColorGroup.Inactive, QPalette.ColorRole.Button, brush1)
        palette.setBrush(QPalette.ColorGroup.Inactive, QPalette.ColorRole.Light, brush2)
        palette.setBrush(QPalette.ColorGroup.Inactive, QPalette.ColorRole.Midlight, brush3)
        palette.setBrush(QPalette.ColorGroup.Inactive, QPalette.ColorRole.Dark, brush4)
        palette.setBrush(QPalette.ColorGroup.Inactive, QPalette.ColorRole.Mid, brush5)
        palette.setBrush(QPalette.ColorGroup.Inactive, QPalette.ColorRole.Text, brush)
        palette.setBrush(QPalette.ColorGroup.Inactive, QPalette.ColorRole.BrightText, brush)
        palette.setBrush(QPalette.ColorGroup.Inactive, QPalette.ColorRole.ButtonText, brush)
        palette.setBrush(QPalette.ColorGroup.Inactive, QPalette.ColorRole.Base, brush6)
        palette.setBrush(QPalette.ColorGroup.Inactive, QPalette.ColorRole.Window, brush1)
        palette.setBrush(QPalette.ColorGroup.Inactive, QPalette.ColorRole.Shadow, brush6)
        palette.setBrush(QPalette.ColorGroup.Inactive, QPalette.ColorRole.AlternateBase, brush4)
        palette.setBrush(QPalette.ColorGroup.Inactive, QPalette.ColorRole.ToolTipBase, brush7)
        palette.setBrush(QPalette.ColorGroup.Inactive, QPalette.ColorRole.ToolTipText, brush6)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette.setBrush(QPalette.ColorGroup.Inactive, QPalette.ColorRole.PlaceholderText, brush8)
#endif
#if QT_VERSION >= QT_VERSION_CHECK(6, 6, 0)
        palette.setBrush(QPalette.ColorGroup.Inactive, QPalette.ColorRole.Accent, brush6)
#endif
        palette.setBrush(QPalette.ColorGroup.Disabled, QPalette.ColorRole.WindowText, brush4)
        palette.setBrush(QPalette.ColorGroup.Disabled, QPalette.ColorRole.Button, brush1)
        palette.setBrush(QPalette.ColorGroup.Disabled, QPalette.ColorRole.Light, brush2)
        palette.setBrush(QPalette.ColorGroup.Disabled, QPalette.ColorRole.Midlight, brush3)
        palette.setBrush(QPalette.ColorGroup.Disabled, QPalette.ColorRole.Dark, brush4)
        palette.setBrush(QPalette.ColorGroup.Disabled, QPalette.ColorRole.Mid, brush5)
        palette.setBrush(QPalette.ColorGroup.Disabled, QPalette.ColorRole.Text, brush4)
        palette.setBrush(QPalette.ColorGroup.Disabled, QPalette.ColorRole.BrightText, brush)
        palette.setBrush(QPalette.ColorGroup.Disabled, QPalette.ColorRole.ButtonText, brush4)
        palette.setBrush(QPalette.ColorGroup.Disabled, QPalette.ColorRole.Base, brush1)
        palette.setBrush(QPalette.ColorGroup.Disabled, QPalette.ColorRole.Window, brush1)
        palette.setBrush(QPalette.ColorGroup.Disabled, QPalette.ColorRole.Shadow, brush6)
        palette.setBrush(QPalette.ColorGroup.Disabled, QPalette.ColorRole.AlternateBase, brush1)
        palette.setBrush(QPalette.ColorGroup.Disabled, QPalette.ColorRole.ToolTipBase, brush7)
        palette.setBrush(QPalette.ColorGroup.Disabled, QPalette.ColorRole.ToolTipText, brush6)
        brush9 = QBrush(QColor(24, 17, 46, 127))
        brush9.setStyle(Qt.BrushStyle.SolidPattern)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette.setBrush(QPalette.ColorGroup.Disabled, QPalette.ColorRole.PlaceholderText, brush9)
#endif
        brush10 = QBrush(QColor(34, 24, 65, 255))
        brush10.setStyle(Qt.BrushStyle.SolidPattern)
#if QT_VERSION >= QT_VERSION_CHECK(6, 6, 0)
        palette.setBrush(QPalette.ColorGroup.Disabled, QPalette.ColorRole.Accent, brush10)
#endif
        check_health_in_progress.setPalette(palette)
        check_health_in_progress.setAutoFillBackground(True)
        self.det_game_label = QLabel(check_health_in_progress)
        self.det_game_label.setObjectName(u"det_game_label")
        self.det_game_label.setGeometry(QRect(230, 20, 201, 41))
        font = QFont()
        font.setPointSize(20)
        self.det_game_label.setFont(font)
        self.verify_checksum = QLabel(check_health_in_progress)
        self.verify_checksum.setObjectName(u"verify_checksum")
        self.verify_checksum.setGeometry(QRect(340, 320, 201, 41))
        self.verify_checksum.setFont(font)
        self.verify_checksum.setAlignment(Qt.AlignmentFlag.AlignLeading|Qt.AlignmentFlag.AlignLeft|Qt.AlignmentFlag.AlignVCenter)
        self.test_save_retention = QLabel(check_health_in_progress)
        self.test_save_retention.setObjectName(u"test_save_retention")
        self.test_save_retention.setGeometry(QRect(340, 400, 221, 41))
        self.test_save_retention.setFont(font)
        self.test_save_retention.setAlignment(Qt.AlignmentFlag.AlignLeading|Qt.AlignmentFlag.AlignLeft|Qt.AlignmentFlag.AlignVCenter)
        self.identify_corruption = QLabel(check_health_in_progress)
        self.identify_corruption.setObjectName(u"identify_corruption")
        self.identify_corruption.setGeometry(QRect(340, 360, 201, 41))
        self.identify_corruption.setFont(font)
        self.identify_corruption.setAlignment(Qt.AlignmentFlag.AlignLeading|Qt.AlignmentFlag.AlignLeft|Qt.AlignmentFlag.AlignVCenter)
        self.test_pins = QLabel(check_health_in_progress)
        self.test_pins.setObjectName(u"test_pins")
        self.test_pins.setGeometry(QRect(340, 280, 201, 41))
        self.test_pins.setFont(font)
        self.test_pins.setAlignment(Qt.AlignmentFlag.AlignLeading|Qt.AlignmentFlag.AlignLeft|Qt.AlignmentFlag.AlignVCenter)
        self.tst_sv_ret_label = QLabel(check_health_in_progress)
        self.tst_sv_ret_label.setObjectName(u"tst_sv_ret_label")
        self.tst_sv_ret_label.setGeometry(QRect(70, 400, 251, 41))
        self.tst_sv_ret_label.setFont(font)
        self.tst_sv_ret_label.setAlignment(Qt.AlignmentFlag.AlignRight|Qt.AlignmentFlag.AlignTrailing|Qt.AlignmentFlag.AlignVCenter)
        self.id_corr_label = QLabel(check_health_in_progress)
        self.id_corr_label.setObjectName(u"id_corr_label")
        self.id_corr_label.setGeometry(QRect(80, 360, 241, 41))
        self.id_corr_label.setFont(font)
        self.id_corr_label.setAlignment(Qt.AlignmentFlag.AlignRight|Qt.AlignmentFlag.AlignTrailing|Qt.AlignmentFlag.AlignVCenter)
        self.test_pins_label = QLabel(check_health_in_progress)
        self.test_pins_label.setObjectName(u"test_pins_label")
        self.test_pins_label.setGeometry(QRect(120, 280, 201, 41))
        self.test_pins_label.setFont(font)
        self.test_pins_label.setAlignment(Qt.AlignmentFlag.AlignRight|Qt.AlignmentFlag.AlignTrailing|Qt.AlignmentFlag.AlignVCenter)
        self.vrfy_chksum_label = QLabel(check_health_in_progress)
        self.vrfy_chksum_label.setObjectName(u"vrfy_chksum_label")
        self.vrfy_chksum_label.setGeometry(QRect(110, 320, 211, 41))
        self.vrfy_chksum_label.setFont(font)
        self.vrfy_chksum_label.setAlignment(Qt.AlignmentFlag.AlignRight|Qt.AlignmentFlag.AlignTrailing|Qt.AlignmentFlag.AlignVCenter)
        self.warning_label = QLabel(check_health_in_progress)
        self.warning_label.setObjectName(u"warning_label")
        self.warning_label.setGeometry(QRect(30, 490, 601, 71))
        self.warning_label.setFont(font)

        self.retranslateUi(check_health_in_progress)

        QMetaObject.connectSlotsByName(check_health_in_progress)
    # setupUi

    def retranslateUi(self, check_health_in_progress):
        check_health_in_progress.setWindowTitle(QCoreApplication.translate("check_health_in_progress", u"Frame", None))
        self.det_game_label.setText(QCoreApplication.translate("check_health_in_progress", u"Detected Game:", None))
        self.verify_checksum.setText(QCoreApplication.translate("check_health_in_progress", u"In Progress...", None))
        self.test_save_retention.setText(QCoreApplication.translate("check_health_in_progress", u"In Progress...", None))
        self.identify_corruption.setText(QCoreApplication.translate("check_health_in_progress", u"In Progress...", None))
        self.test_pins.setText(QCoreApplication.translate("check_health_in_progress", u"In Progress...", None))
        self.tst_sv_ret_label.setText(QCoreApplication.translate("check_health_in_progress", u"Test Save Retention:", None))
        self.id_corr_label.setText(QCoreApplication.translate("check_health_in_progress", u"Identify Corruption:", None))
        self.test_pins_label.setText(QCoreApplication.translate("check_health_in_progress", u"Test Pins:", None))
        self.vrfy_chksum_label.setText(QCoreApplication.translate("check_health_in_progress", u"Verify Checksum:", None))
        self.warning_label.setText(QCoreApplication.translate("check_health_in_progress", u"DO NOT UNPLUG THE SCARAB OR ANY MODULES", None))
    # retranslateUi

