# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'check_health_custom_scan.ui'
##
## Created by: Qt User Interface Compiler version 6.10.2
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QBrush, QColor, QConicalGradient, QCursor,
    QFont, QFontDatabase, QGradient, QIcon,
    QImage, QKeySequence, QLinearGradient, QPainter,
    QPalette, QPixmap, QRadialGradient, QTransform)
from PySide6.QtWidgets import (QApplication, QCheckBox, QFrame, QLabel,
    QPushButton, QSizePolicy, QWidget)

class Ui_check_health_custom_scan(object):
    def setupUi(self, check_health_custom_scan):
        if not check_health_custom_scan.objectName():
            check_health_custom_scan.setObjectName(u"check_health_custom_scan")
        check_health_custom_scan.resize(650, 600)
        palette = QPalette()
        brush = QBrush(QColor(255, 255, 255, 255))
        brush.setStyle(Qt.BrushStyle.SolidPattern)
        palette.setBrush(QPalette.ColorGroup.Active, QPalette.ColorRole.WindowText, brush)
        brush1 = QBrush(QColor(48, 34, 93, 255))
        brush1.setStyle(Qt.BrushStyle.SolidPattern)
        palette.setBrush(QPalette.ColorGroup.Active, QPalette.ColorRole.Button, brush1)
        brush2 = QBrush(QColor(72, 51, 139, 255))
        brush2.setStyle(Qt.BrushStyle.SolidPattern)
        palette.setBrush(QPalette.ColorGroup.Active, QPalette.ColorRole.Light, brush2)
        brush3 = QBrush(QColor(60, 42, 116, 255))
        brush3.setStyle(Qt.BrushStyle.SolidPattern)
        palette.setBrush(QPalette.ColorGroup.Active, QPalette.ColorRole.Midlight, brush3)
        brush4 = QBrush(QColor(24, 17, 46, 255))
        brush4.setStyle(Qt.BrushStyle.SolidPattern)
        palette.setBrush(QPalette.ColorGroup.Active, QPalette.ColorRole.Dark, brush4)
        brush5 = QBrush(QColor(200, 200, 200, 255))
        brush5.setStyle(Qt.BrushStyle.SolidPattern)
        palette.setBrush(QPalette.ColorGroup.Active, QPalette.ColorRole.Mid, brush5)
        palette.setBrush(QPalette.ColorGroup.Active, QPalette.ColorRole.Text, brush)
        palette.setBrush(QPalette.ColorGroup.Active, QPalette.ColorRole.BrightText, brush)
        palette.setBrush(QPalette.ColorGroup.Active, QPalette.ColorRole.ButtonText, brush)
        brush6 = QBrush(QColor(0, 0, 0, 255))
        brush6.setStyle(Qt.BrushStyle.SolidPattern)
        palette.setBrush(QPalette.ColorGroup.Active, QPalette.ColorRole.Base, brush6)
        palette.setBrush(QPalette.ColorGroup.Active, QPalette.ColorRole.Window, brush1)
        palette.setBrush(QPalette.ColorGroup.Active, QPalette.ColorRole.Shadow, brush6)
        palette.setBrush(QPalette.ColorGroup.Active, QPalette.ColorRole.AlternateBase, brush4)
        brush7 = QBrush(QColor(255, 255, 220, 255))
        brush7.setStyle(Qt.BrushStyle.SolidPattern)
        palette.setBrush(QPalette.ColorGroup.Active, QPalette.ColorRole.ToolTipBase, brush7)
        palette.setBrush(QPalette.ColorGroup.Active, QPalette.ColorRole.ToolTipText, brush6)
        brush8 = QBrush(QColor(255, 255, 255, 127))
        brush8.setStyle(Qt.BrushStyle.SolidPattern)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette.setBrush(QPalette.ColorGroup.Active, QPalette.ColorRole.PlaceholderText, brush8)
#endif
#if QT_VERSION >= QT_VERSION_CHECK(6, 6, 0)
        palette.setBrush(QPalette.ColorGroup.Active, QPalette.ColorRole.Accent, brush6)
#endif
        palette.setBrush(QPalette.ColorGroup.Inactive, QPalette.ColorRole.WindowText, brush)
        palette.setBrush(QPalette.ColorGroup.Inactive, QPalette.ColorRole.Button, brush1)
        palette.setBrush(QPalette.ColorGroup.Inactive, QPalette.ColorRole.Light, brush2)
        palette.setBrush(QPalette.ColorGroup.Inactive, QPalette.ColorRole.Midlight, brush3)
        palette.setBrush(QPalette.ColorGroup.Inactive, QPalette.ColorRole.Dark, brush4)
        brush9 = QBrush(QColor(32, 23, 62, 255))
        brush9.setStyle(Qt.BrushStyle.SolidPattern)
        palette.setBrush(QPalette.ColorGroup.Inactive, QPalette.ColorRole.Mid, brush9)
        palette.setBrush(QPalette.ColorGroup.Inactive, QPalette.ColorRole.Text, brush)
        palette.setBrush(QPalette.ColorGroup.Inactive, QPalette.ColorRole.BrightText, brush)
        palette.setBrush(QPalette.ColorGroup.Inactive, QPalette.ColorRole.ButtonText, brush)
        palette.setBrush(QPalette.ColorGroup.Inactive, QPalette.ColorRole.Base, brush6)
        palette.setBrush(QPalette.ColorGroup.Inactive, QPalette.ColorRole.Window, brush1)
        palette.setBrush(QPalette.ColorGroup.Inactive, QPalette.ColorRole.Shadow, brush6)
        palette.setBrush(QPalette.ColorGroup.Inactive, QPalette.ColorRole.AlternateBase, brush4)
        palette.setBrush(QPalette.ColorGroup.Inactive, QPalette.ColorRole.ToolTipBase, brush7)
        palette.setBrush(QPalette.ColorGroup.Inactive, QPalette.ColorRole.ToolTipText, brush6)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette.setBrush(QPalette.ColorGroup.Inactive, QPalette.ColorRole.PlaceholderText, brush8)
#endif
#if QT_VERSION >= QT_VERSION_CHECK(6, 6, 0)
        palette.setBrush(QPalette.ColorGroup.Inactive, QPalette.ColorRole.Accent, brush6)
#endif
        palette.setBrush(QPalette.ColorGroup.Disabled, QPalette.ColorRole.WindowText, brush4)
        palette.setBrush(QPalette.ColorGroup.Disabled, QPalette.ColorRole.Button, brush1)
        palette.setBrush(QPalette.ColorGroup.Disabled, QPalette.ColorRole.Light, brush2)
        palette.setBrush(QPalette.ColorGroup.Disabled, QPalette.ColorRole.Midlight, brush3)
        palette.setBrush(QPalette.ColorGroup.Disabled, QPalette.ColorRole.Dark, brush4)
        palette.setBrush(QPalette.ColorGroup.Disabled, QPalette.ColorRole.Mid, brush9)
        palette.setBrush(QPalette.ColorGroup.Disabled, QPalette.ColorRole.Text, brush4)
        palette.setBrush(QPalette.ColorGroup.Disabled, QPalette.ColorRole.BrightText, brush)
        palette.setBrush(QPalette.ColorGroup.Disabled, QPalette.ColorRole.ButtonText, brush4)
        palette.setBrush(QPalette.ColorGroup.Disabled, QPalette.ColorRole.Base, brush1)
        palette.setBrush(QPalette.ColorGroup.Disabled, QPalette.ColorRole.Window, brush1)
        palette.setBrush(QPalette.ColorGroup.Disabled, QPalette.ColorRole.Shadow, brush6)
        palette.setBrush(QPalette.ColorGroup.Disabled, QPalette.ColorRole.AlternateBase, brush1)
        palette.setBrush(QPalette.ColorGroup.Disabled, QPalette.ColorRole.ToolTipBase, brush7)
        palette.setBrush(QPalette.ColorGroup.Disabled, QPalette.ColorRole.ToolTipText, brush6)
        brush10 = QBrush(QColor(24, 17, 46, 127))
        brush10.setStyle(Qt.BrushStyle.SolidPattern)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette.setBrush(QPalette.ColorGroup.Disabled, QPalette.ColorRole.PlaceholderText, brush10)
#endif
        brush11 = QBrush(QColor(34, 24, 65, 255))
        brush11.setStyle(Qt.BrushStyle.SolidPattern)
#if QT_VERSION >= QT_VERSION_CHECK(6, 6, 0)
        palette.setBrush(QPalette.ColorGroup.Disabled, QPalette.ColorRole.Accent, brush11)
#endif
        check_health_custom_scan.setPalette(palette)
        check_health_custom_scan.setAutoFillBackground(True)
        self.det_game_label = QLabel(check_health_custom_scan)
        self.det_game_label.setObjectName(u"det_game_label")
        self.det_game_label.setGeometry(QRect(230, 20, 201, 41))
        font = QFont()
        font.setPointSize(20)
        self.det_game_label.setFont(font)
        self.custom_scan_button = QPushButton(check_health_custom_scan)
        self.custom_scan_button.setObjectName(u"custom_scan_button")
        self.custom_scan_button.setGeometry(QRect(200, 470, 251, 71))
        self.custom_scan_button.setFont(font)
        self.name_label = QLabel(check_health_custom_scan)
        self.name_label.setObjectName(u"name_label")
        self.name_label.setGeometry(QRect(160, 290, 201, 41))
        self.name_label.setFont(font)
        self.name_label.setAlignment(Qt.AlignmentFlag.AlignRight|Qt.AlignmentFlag.AlignTrailing|Qt.AlignmentFlag.AlignVCenter)
        self.rom_sz_label = QLabel(check_health_custom_scan)
        self.rom_sz_label.setObjectName(u"rom_sz_label")
        self.rom_sz_label.setGeometry(QRect(160, 330, 201, 41))
        self.rom_sz_label.setFont(font)
        self.rom_sz_label.setAlignment(Qt.AlignmentFlag.AlignRight|Qt.AlignmentFlag.AlignTrailing|Qt.AlignmentFlag.AlignVCenter)
        self.chip_label = QLabel(check_health_custom_scan)
        self.chip_label.setObjectName(u"chip_label")
        self.chip_label.setGeometry(QRect(120, 370, 241, 41))
        self.chip_label.setFont(font)
        self.chip_label.setAlignment(Qt.AlignmentFlag.AlignRight|Qt.AlignmentFlag.AlignTrailing|Qt.AlignmentFlag.AlignVCenter)
        self.hdr_chk_label = QLabel(check_health_custom_scan)
        self.hdr_chk_label.setObjectName(u"hdr_chk_label")
        self.hdr_chk_label.setGeometry(QRect(120, 410, 241, 41))
        self.hdr_chk_label.setFont(font)
        self.hdr_chk_label.setAlignment(Qt.AlignmentFlag.AlignRight|Qt.AlignmentFlag.AlignTrailing|Qt.AlignmentFlag.AlignVCenter)
        self.test_pins_box = QCheckBox(check_health_custom_scan)
        self.test_pins_box.setObjectName(u"test_pins_box")
        self.test_pins_box.setGeometry(QRect(380, 300, 20, 31))
        self.test_pins_box.setFont(font)
        self.test_pins_box.setIconSize(QSize(32, 32))
        self.test_pins_box.setChecked(False)
        self.test_pins_box.setTristate(False)
        self.checksum_box = QCheckBox(check_health_custom_scan)
        self.checksum_box.setObjectName(u"checksum_box")
        self.checksum_box.setGeometry(QRect(380, 340, 20, 31))
        self.checksum_box.setFont(font)
        self.checksum_box.setIconSize(QSize(32, 32))
        self.checksum_box.setChecked(False)
        self.checksum_box.setTristate(False)
        self.corruption_box = QCheckBox(check_health_custom_scan)
        self.corruption_box.setObjectName(u"corruption_box")
        self.corruption_box.setGeometry(QRect(380, 380, 20, 31))
        self.corruption_box.setFont(font)
        self.corruption_box.setIconSize(QSize(32, 32))
        self.corruption_box.setChecked(False)
        self.corruption_box.setTristate(False)
        self.test_save_box = QCheckBox(check_health_custom_scan)
        self.test_save_box.setObjectName(u"test_save_box")
        self.test_save_box.setGeometry(QRect(380, 420, 20, 31))
        self.test_save_box.setFont(font)
        self.test_save_box.setIconSize(QSize(32, 32))
        self.test_save_box.setChecked(False)
        self.test_save_box.setTristate(False)
        self.label = QLabel(check_health_custom_scan)
        self.label.setObjectName(u"label")
        self.label.setGeometry(QRect(190, 80, 266, 200))
        self.cart_image = QLabel(check_health_custom_scan)
        self.cart_image.setObjectName(u"cart_image")
        self.cart_image.setGeometry(QRect(190, 70, 266, 200))

        self.retranslateUi(check_health_custom_scan)

        QMetaObject.connectSlotsByName(check_health_custom_scan)
    # setupUi

    def retranslateUi(self, check_health_custom_scan):
        check_health_custom_scan.setWindowTitle(QCoreApplication.translate("check_health_custom_scan", u"Frame", None))
        self.det_game_label.setText(QCoreApplication.translate("check_health_custom_scan", u"Detected Game:", None))
        self.custom_scan_button.setText(QCoreApplication.translate("check_health_custom_scan", u"Check Health", None))
        self.name_label.setText(QCoreApplication.translate("check_health_custom_scan", u"Test Pins:", None))
        self.rom_sz_label.setText(QCoreApplication.translate("check_health_custom_scan", u"Verify Checksum:", None))
        self.chip_label.setText(QCoreApplication.translate("check_health_custom_scan", u"Identify Corruption:", None))
        self.hdr_chk_label.setText(QCoreApplication.translate("check_health_custom_scan", u"Test Save Retention:", None))
        self.test_pins_box.setText("")
        self.checksum_box.setText("")
        self.corruption_box.setText("")
        self.test_save_box.setText("")
        self.label.setText("")
        self.cart_image.setText("")
    # retranslateUi

